apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
  - port: 5432
  selector:
    app: database
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - image: bitnami/postgresql:13
        name: database
        env:
        - name: POSTGRESQL_POSTGRES_PASSWORD
          valueFrom:
              secretKeyRef:
                  name: icf-secret
                  key: postgresql_root_password
        - name: POSTGRESQL_DATABASE
          value: icf_navigator
        - name: POSTGRESQL_USERNAME
          valueFrom:
              secretKeyRef:
                  name: icf-secret
                  key: postgresql_username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
              secretKeyRef:
                  name: icf-secret
                  key: postgresql_password
        # livenessProbe:
        #     exec:
        #         command:
        #             - bash
        #             - "-c"
        #             - |
        #                 mysql -u root -p$MYSQL_ROOT_PASSWORD -h 127.0.0.1 -e 'SELECT 1'
        #     initialDelaySeconds: 30
        #     periodSeconds: 10
        #     timeoutSeconds: 5
        # readinessProbe:
        #     exec:
        #         command:
        #             - bash
        #             - "-c"
        #             - |
        #                 mysql -u root -p$MYSQL_ROOT_PASSWORD -h 127.0.0.1 -e 'SELECT 1'
        #     initialDelaySeconds: 5
        #     periodSeconds: 2
        #     timeoutSeconds: 1
        ports:
        - containerPort: 5432
          name: database
        volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /bitnami/postgresql
      volumes:
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: postgresql-pv-claim-auto
