apiVersion: v1
kind: Service
metadata:
  name: navigator
spec:
  ports:
  - port: 8080
  selector:
    app: navigator
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: navigator
spec:
  selector:
    matchLabels:
      app: navigator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: navigator
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: icf-navigator-sites-enabled-configmap
        - name: staticfiles
          emptyDir: {}
      initContainers:
        - name: migrate
          image: jrutecht/icf_navigator:latest
          env:
          - name: ICF_DATABASE_HOST
            value: database
          - name: ICF_DATABASE_USER
            valueFrom:
                secretKeyRef:
                    name: icf-secret
                    key: postgresql_username
          - name: ICF_DATABASE_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: icf-secret
                    key: postgresql_password
          - name: ICF_DJANGO_SECRET_KEY
            valueFrom:
                secretKeyRef:
                    name: icf-secret
                    key: django_secret_key
          command: ["python", "manage.py", "migrate"]
        - name: collectstatic
          image: jrutecht/icf_navigator:latest
          env:
          - name: ICF_DATABASE_HOST
            value: database
          - name: ICF_DATABASE_USER
            valueFrom:
                secretKeyRef:
                    name: icf-secret
                    key: postgresql_username
          - name: ICF_DATABASE_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: icf-secret
                    key: postgresql_password
          - name: ICF_DJANGO_SECRET_KEY
            valueFrom:
                secretKeyRef:
                    name: icf-secret
                    key: django_secret_key
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          volumeMounts:
            - name: staticfiles
              mountPath: /var/www/html
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/
          - name: staticfiles
            mountPath: /var/www/html
      - name: navigator
        image: jrutecht/icf_navigator:latest
        env:
        - name: ICF_DATABASE_HOST
          value: database
        - name: ICF_DATABASE_USER
          valueFrom:
              secretKeyRef:
                  name: icf-secret
                  key: postgresql_username
        - name: ICF_DATABASE_PASSWORD
          valueFrom:
              secretKeyRef:
                  name: icf-secret
                  key: postgresql_password
        - name: ICF_DJANGO_SECRET_KEY
          valueFrom:
              secretKeyRef:
                  name: icf-secret
                  key: django_secret_key
        ports:
        - containerPort: 3000
          protocol: TCP
