apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim-auto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: glusterfs-storage
  resources:
    requests:
      storage: 1Gi
