# Generated by Django 3.1.14 on 2022-06-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CannedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EditText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField()),
                ('logic', models.TextField(default='True')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('core.yesnoquestion', 'yes no question'), ('core.yesnoexplainquestion', 'yes no explain question'), ('core.freetextquestion', 'free text question'), ('core.multiselectquestion', 'multi select question'), ('core.textlistquestion', 'text list question'), ('core.contactquestion', 'contact question'), ('core.integerquestion', 'integer question'), ('core.customquestion', 'custom question')], db_index=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('extra_text', models.TextField(blank=True)),
                ('order', models.FloatField(unique=True)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('explain_when', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('B', 'Both')], max_length=1, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('minimum_required', models.IntegerField(blank=True, null=True)),
                ('allow_more', models.BooleanField(default=False)),
                ('custom_form', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.FloatField(unique=True)),
                ('template', models.TextField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consentform')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
            options={
                'get_latest_by': 'last_change',
            },
        ),
    ]
