# Generated by Django 3.1.2 on 2020-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(default='question', max_length=50),
        ),
    ]
