# Generated by Django 3.1.2 on 2020-10-04 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_textlistquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textlistquestion',
            name='id',
        ),
        migrations.AddField(
            model_name='textlistquestion',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.question'),
            preserve_default=False,
        ),
    ]
