# Generated by Django 3.1.2 on 2020-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consentform_authorized_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.FloatField(unique=True)),
                ('template', models.TextField()),
                ('questions', models.ManyToManyField(to='core.Question')),
            ],
        ),
    ]
