# Generated by Django 3.1.2 on 2020-10-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_qtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.question')),
            ],
            bases=('core.question',),
        ),
    ]
