# Generated by Django 3.1.2 on 2020-12-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='section',
            name='questions',
        ),
        migrations.CreateModel(
            name='QGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField()),
                ('logic', models.TextField(default='True')),
                ('questions', models.ManyToManyField(blank=True, to='core.Question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('order', 'section')},
            },
        ),
    ]
