# Generated by Django 3.1.2 on 2020-10-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_integerquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNoExplainQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.question')),
                ('explain_when', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('B', 'Both')], max_length=1)),
            ],
            bases=('core.question',),
        ),
    ]
