# Generated by Django 3.1.2 on 2020-10-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_response_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('form', 'question')},
        ),
    ]
