# Generated by Django 3.1.2 on 2021-03-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210126_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='custom_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='explain_when',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('B', 'Both')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='minimum_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('core.yesnoquestion', 'yes no question'), ('core.yesnoexplainquestion', 'yes no explain question'), ('core.freetextquestion', 'free text question'), ('core.multiselectquestion', 'multi select question'), ('core.textlistquestion', 'text list question'), ('core.contactquestion', 'contact question'), ('core.integerquestion', 'integer question'), ('core.customquestion', 'custom question')], db_index=True, max_length=255),
        ),
    ]
