# Generated by Django 3.1.2 on 2021-03-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210301_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_text',
            field=models.TextField(blank=True),
        ),
    ]
