# Generated by Django 3.1.2 on 2021-04-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_extra_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.response')),
            ],
        ),
    ]
