# Generated by Django 3.1.2 on 2021-04-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_edittext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='canned',
        ),
        migrations.RemoveField(
            model_name='question',
            name='canned_logic',
        ),
        migrations.AddField(
            model_name='question',
            name='canned_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canned_no', to='core.cannedtext'),
        ),
        migrations.AddField(
            model_name='question',
            name='canned_yes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canned_yes', to='core.cannedtext'),
        ),
    ]
