# Generated by Django 3.1.2 on 2022-01-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210408_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='last_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
