# Generated by Django 3.1.2 on 2022-02-06 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from users.models import ADUser


class Migration(migrations.Migration):

    user_id = ADUser.objects.all().first().id

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_response_last_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'get_latest_by': 'last_change'},
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(default=user_id, on_delete=django.db.models.deletion.CASCADE, to='users.aduser'),
            preserve_default=False,
        ),
    ]
